package br.com.maplink2.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-11-06T22:58:56.953-02:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "Route", 
                  wsdlLocation = "http://services.maplink.com.br/webservices/v3/route/route.asmx?wsdl",
                  targetNamespace = "http://webservices.maplink2.com.br") 
public class Route extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservices.maplink2.com.br", "Route");
    public final static QName RouteSoap = new QName("http://webservices.maplink2.com.br", "RouteSoap");
    public final static QName RouteSoap12 = new QName("http://webservices.maplink2.com.br", "RouteSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://services.maplink.com.br/webservices/v3/route/route.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Route.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://services.maplink.com.br/webservices/v3/route/route.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Route(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Route(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Route() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Route(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Route(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Route(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns RouteSoap
     */
    @WebEndpoint(name = "RouteSoap")
    public RouteSoap getRouteSoap() {
        return super.getPort(RouteSoap, RouteSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RouteSoap
     */
    @WebEndpoint(name = "RouteSoap")
    public RouteSoap getRouteSoap(WebServiceFeature... features) {
        return super.getPort(RouteSoap, RouteSoap.class, features);
    }
    /**
     *
     * @return
     *     returns RouteSoap
     */
    @WebEndpoint(name = "RouteSoap12")
    public RouteSoap getRouteSoap12() {
        return super.getPort(RouteSoap12, RouteSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RouteSoap
     */
    @WebEndpoint(name = "RouteSoap12")
    public RouteSoap getRouteSoap12(WebServiceFeature... features) {
        return super.getPort(RouteSoap12, RouteSoap.class, features);
    }

}
