package br.com.maplink2.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-11-06T22:58:56.911-02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://webservices.maplink2.com.br", name = "RouteSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface RouteSoap {

    /**
     * Retorna a rota entre os pontos informados com até duas alternativas (caso exista)
     */
    @WebResult(name = "getRouteWithAlternativesResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "getRouteWithAlternatives", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetRouteWithAlternatives")
    @WebMethod(action = "http://webservices.maplink2.com.br/getRouteWithAlternatives")
    @ResponseWrapper(localName = "getRouteWithAlternativesResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetRouteWithAlternativesResponse")
    public br.com.maplink2.webservices.AlternativeRouteInfo getRouteWithAlternatives(
        @WebParam(name = "rs", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.ArrayOfRouteStop rs,
        @WebParam(name = "ro", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.RouteOptions ro,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        java.lang.String token
    );

    /**
     * Gera o resumo da rota.
     */
    @WebResult(name = "getRouteSummaryResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "getRouteSummary", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetRouteSummary")
    @WebMethod(action = "http://webservices.maplink2.com.br/getRouteSummary")
    @ResponseWrapper(localName = "getRouteSummaryResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetRouteSummaryResponse")
    public br.com.maplink2.webservices.ArrayOfRouteSummary getRouteSummary(
        @WebParam(name = "rs", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.ArrayOfRouteStop rs,
        @WebParam(name = "ro", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.RouteOptions ro,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        java.lang.String token
    );

    /**
     * Gera a descrição da rota.
     */
    @WebResult(name = "getRouteDescriptionResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "getRouteDescription", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetRouteDescription")
    @WebMethod(action = "http://webservices.maplink2.com.br/getRouteDescription")
    @ResponseWrapper(localName = "getRouteDescriptionResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetRouteDescriptionResponse")
    public br.com.maplink2.webservices.ArrayOfSegmentDescription getRouteDescription(
        @WebParam(name = "rs", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.ArrayOfRouteStop rs,
        @WebParam(name = "ro", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.RouteOptions ro,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        java.lang.String token
    );

    /**
     * Retorna rotas entre os pontos de origem e destinos informados.
     */
    @WebResult(name = "getMultiRouteResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "getMultiRoute", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetMultiRoute")
    @WebMethod(action = "http://webservices.maplink2.com.br/getMultiRoute")
    @ResponseWrapper(localName = "getMultiRouteResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetMultiRouteResponse")
    public br.com.maplink2.webservices.MultiRoute getMultiRoute(
        @WebParam(name = "request", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.ArrayOfMultiRouteRequest request,
        @WebParam(name = "ro", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.RouteOptions ro,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        java.lang.String token
    );

    /**
     * Calcula os totais da rota informada.
     */
    @WebResult(name = "getRouteTotalsResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "getRouteTotals", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetRouteTotals")
    @WebMethod(action = "http://webservices.maplink2.com.br/getRouteTotals")
    @ResponseWrapper(localName = "getRouteTotalsResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetRouteTotalsResponse")
    public br.com.maplink2.webservices.RouteTotals getRouteTotals(
        @WebParam(name = "rs", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.ArrayOfRouteStop rs,
        @WebParam(name = "ro", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.RouteOptions ro,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        java.lang.String token
    );

    /**
     * Calcula a rota e gera a imagem do mapa.
     */
    @WebResult(name = "getRouteWithMapResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "getRouteWithMap", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetRouteWithMap")
    @WebMethod(action = "http://webservices.maplink2.com.br/getRouteWithMap")
    @ResponseWrapper(localName = "getRouteWithMapResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetRouteWithMapResponse")
    public br.com.maplink2.webservices.RouteInfo getRouteWithMap(
        @WebParam(name = "rs", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.ArrayOfRouteStop rs,
        @WebParam(name = "ro", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.RouteOptions ro,
        @WebParam(name = "mo", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.MapOptions mo,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        java.lang.String token
    );

    /**
     * Retorna a rota entre os pontos informados.
     */
    @WebResult(name = "getRouteResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "getRoute", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetRoute")
    @WebMethod(action = "http://webservices.maplink2.com.br/getRoute")
    @ResponseWrapper(localName = "getRouteResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetRouteResponse")
    public br.com.maplink2.webservices.RouteInfo getRoute(
        @WebParam(name = "rs", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.ArrayOfRouteStop rs,
        @WebParam(name = "ro", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.RouteOptions ro,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        java.lang.String token
    );

    /**
     * Calcula os totais das rotas informadas no array.
     */
    @WebResult(name = "GetRouteTotalsBatchResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "GetRouteTotalsBatch", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetRouteTotalsBatch")
    @WebMethod(operationName = "GetRouteTotalsBatch", action = "http://webservices.maplink2.com.br/GetRouteTotalsBatch")
    @ResponseWrapper(localName = "GetRouteTotalsBatchResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetRouteTotalsBatchResponse")
    public br.com.maplink2.webservices.ArrayOfRouteTotals getRouteTotalsBatch(
        @WebParam(name = "ra", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.ArrayOfRouteArray ra,
        @WebParam(name = "ro", targetNamespace = "http://webservices.maplink2.com.br")
        br.com.maplink2.webservices.RouteOptions ro,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        java.lang.String token
    );
}
